### ISSUE TITLE
List of signaling servers

### ISSUE THREAD

**Issue by leplatrem** [y-js/y-webrtc#1]
It looks like the default one is currently down. It would be nice to provide a small list somewhere (wiki?) to allow developpers to set it up quickly :)

For example, I tried this:
```
var connector = new Y.WebRTC("leaflet-yjs", {url: "https://signaling.simplewebrtc.com"})
```
with no luck :/

**Comment by leplatrem** [comment]
OH, ``https://signaling.simplewebrtc.com:443/`` works though :)

**Comment by DadaMonad** [comment]
Oh.. haven't seen this one :( sorry. I'll close it now
